set(AOIP_SOURCE_DIR "" CACHE PATH "Optional existing AoIP-lib checkout")
if(NOT TARGET AoIP::core)
  if(AOIP_SOURCE_DIR)
    add_subdirectory("${AOIP_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/aoip")
  elseif(EXISTS "${CMAKE_CURRENT_LIST_DIR}/../external/AoIP-lib/CMakeLists.txt")
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../external/AoIP-lib" "${CMAKE_BINARY_DIR}/aoip")
  else()
    find_package(AoIP 2.1 CONFIG REQUIRED)
  endif()
endif()
